name: DevOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      # AWS
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

      # ui
      UI_ECR_REPO_NAME: ${{ secrets.UI_ECR_REPO_NAME }}
      UI_REPOSITORY_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.UI_ECR_REPO_NAME }}


      # orders
      ORDERS_ECR_REPO_NAME: ${{ secrets.ORDERS_ECR_REPO_NAME }}
      ORDERS_REPOSITORY_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ORDERS_ECR_REPO_NAME }}

      # catalog
      CATALOG_ECR_REPO_NAME: ${{ secrets.CATALOG_ECR_REPO_NAME }}
      CATALOG_REPOSITORY_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.CATALOG_ECR_REPO_NAME }}

      # checkout
      CHECKOUT_ECR_REPO_NAME: ${{ secrets.CHECKOUT_ECR_REPO_NAME }}
      CHECKOUT_REPOSITORY_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.CHECKOUT_ECR_REPO_NAME }}
      
      # cart
      CART_ECR_REPO_NAME: ${{ secrets.CART_ECR_REPO_NAME }}
      CART_REPOSITORY_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.CART_ECR_REPO_NAME }}

    steps:
      # 1️⃣ Check Docker
      - name: Check Docker Version
        run: docker --version

      - name: Docker Info
        run: docker info

      # 2️⃣ Clean + Checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # 3️⃣ Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 4️⃣ SonarQube Scan - cart
      - name: SonarQube Scan cart
        working-directory: src/cart
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=cart \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      # 5️⃣ SonarQube Scan - ui
      - name: SonarQube Scan Backend
        working-directory: src/ui
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=ui \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      # 5️⃣ SonarQube Scan - orders
      - name: SonarQube Scan orders
        working-directory: src/orders
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=orders \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      # 5️⃣ SonarQube Scan - catalog
      - name: SonarQube Scan catalog
        working-directory: src/catalog
        run: |
          sonar-scanner \
            -Dsonar.projectKey=catalog \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      # 5️⃣ SonarQube Scan - checkout
      - name: SonarQube Scan checkout
        working-directory: src/checkout
        run: |
          sonar-scanner \
            -Dsonar.projectKey=checkout \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN


      # 6️⃣ Quality Gate - ui
      - name: SonarQube Quality Gate ui
        uses: sonarsource/sonarqube-quality-gate-action@v1
        with:
          scanMetadataReportFile: src/ui/.scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # 6️⃣ Quality Gate - catalog
      - name: SonarQube Quality Gate catalog
        uses: sonarsource/sonarqube-quality-gate-action@v1
        with:
          scanMetadataReportFile: src/catalog/.scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # 6️⃣ Quality Gate - orders
      - name: SonarQube Quality Gate orders
        uses: sonarsource/sonarqube-quality-gate-action@v1
        with:
          scanMetadataReportFile: src/orders/.scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # 6️⃣ Quality Gate - checkout
      - name: SonarQube Quality Gate checkout
        uses: sonarsource/sonarqube-quality-gate-action@v1
        with:
          scanMetadataReportFile: src/checkout/.scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # 6️⃣ Quality Gate - cart
      - name: SonarQube Quality Gate cart
        uses: sonarsource/sonarqube-quality-gate-action@v1
        with:
          scanMetadataReportFile: src/cart/.scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # 7️⃣ Trivy File Scan
      - name: Trivy FS Scan ui
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          scan-type: 'fs'
          scan-ref: 'src/ui'
          output: 'trivy-frontend.txt'
      # 7️⃣ Trivy File Scan
      - name: Trivy FS Scan catalog
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          scan-type: 'fs'
          scan-ref: 'src/catalog'
          output: 'trivy-backend.txt'
      # 7️⃣ Trivy File Scan
      - name: Trivy FS Scan orders
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          scan-type: 'fs'
          scan-ref: 'src/orders'
          output: 'trivy-backend.txt'
      # 7️⃣ Trivy File Scan
      - name: Trivy FS Scan cart
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          scan-type: 'fs'
          scan-ref: 'src/cart'
          output: 'trivy-backend.txt'
      # 7️⃣ Trivy File Scan
      - name: Trivy FS Scan Backend
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          scan-type: 'fs'
          scan-ref: 'src/checkout'
          output: 'trivy-backend.txt'

      # 8️⃣ Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      # 9️⃣ Login to ECR
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 🔟 Build + Push ui
      - name: Build & Push ui Docker Image
        working-directory: src/ui
        run: |
          docker build -t $UI_ECR_REPO_NAME .
          docker tag $UI_ECR_REPO_NAME $UI_REPOSITORY_URI:${{ github.run_number }}
          docker push $UI_REPOSITORY_URI:${{ github.run_number }}

      # 🔟 Build + Push cart
      - name: Build & Push cart Docker Image
        working-directory: src/cart
        run: |
          docker build -t $CART_ECR_REPO_NAME .
          docker tag $CART_ECR_REPO_NAME $CART_REPOSITORY_URI:${{ github.run_number }}
          docker push $CART_REPOSITORY_URI:${{ github.run_number }}

      # 🔟 Build + Push catalog
      - name: Build & Push catalog Docker Image
        working-directory: src/catalog
        run: |
          docker build -t $CATALOG_ECR_REPO_NAME .
          docker tag $CATALOG_ECR_REPO_NAME $CATALOG_REPOSITORY_URI:${{ github.run_number }}
          docker push $CATALOG_REPOSITORY_URI:${{ github.run_number }}

      # 🔟 Build + Push orders
      - name: Build & Push orders Docker Image
        working-directory: src/orders
        run: |
          docker build -t $orders_ECR_REPO_NAME .
          docker tag $orders_ECR_REPO_NAME $orders_REPOSITORY_URI:${{ github.run_number }}
          docker push $orders_REPOSITORY_URI:${{ github.run_number }}


      # 1️⃣1️⃣ Build + Push Backend
      - name: Build & Push checkout Docker Image
        working-directory: src/checkout 
        run: |
          docker build -t $checkout_ECR_REPO_NAME .
          docker tag $checkout_ECR_REPO_NAME $checkout_REPOSITORY_URI:${{ github.run_number }}
          docker push $checkout_REPOSITORY_URI:${{ github.run_number }}

      # 1️⃣2️⃣ Trivy Image Scan
      - name: Trivy Image Scan ui
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: ${{ env.UI_REPOSITORY_URI }}:${{ github.run_number }}
          output: 'trivy-ui-image.txt'

      - name: Trivy Image Scan cart
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: ${{ env.CART_REPOSITORY_URI }}:${{ github.run_number }}
          output: 'trivy-cart-image.txt'
      - name: Trivy Image Scan catalog
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: ${{ env.CATALOG_REPOSITORY_URI }}:${{ github.run_number }}
          output: 'trivy-catalog-image.txt'

      - name: Trivy Image Scan checkout
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: ${{ env.CHECKOUT_REPOSITORY_URI }}:${{ github.run_number }}
          output: 'trivy-checkout-image.txt'
      - name: Trivy Image Scan orders
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: ${{ env.ORDERS_REPOSITORY_URI }}:${{ github.run_number }}
          output: 'trivy-orders-image.txt'

